version: '3'

services:
  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "my_password"
      POSTGRES_USER: "my_user"
      POSTGRES_DB: "db"
  web:
    build: .
    command: gunicorn -c gconfig.py --log-file=- my_openshift.wsgi:application
    volumes:
      - .:/code
    ports:
      - 443:80
    depends_on:
     - postgresql
volumes:
  code: